### ISSUE TITLE
How to pass multiple flags to cvEncodeImage ?

### ISSUE THREAD

**Issue by turric4n** [Laex/Delphi-OpenCV#100]
Hi we are trying to pass multiple encoding flags/params to function cvEncodeImage(const ext: pCvChar; const image: pCvArr; const params: PInteger = nil): pCvMat; cdecl;

params is PInteger. How can pass parameters? What is the best way to do it?

**Comment by Laex** [comment]
Var
P: array of Integer;

P:=[CV_IMWRITE_PNG_COMPRESSION,9];
R:=cvEncodeImage('png', image, @P[0]);

**Comment by turric4n** [comment]
Thanks Laex
