### ISSUE TITLE
Whether the opencv‘s mat class is supported in the current version？what in unit file defined ？

### ISSUE THREAD

**Issue by shichuanq** [Laex/Delphi-OpenCV#102]
Whether the opencv‘s mat class is supported in the current version？what in unit file defined ？

thanks

**Comment by zzsczz** [comment]
opencv‘s mat class is in cpp domain.

delphi  use c style interface

**Comment by blaisexen** [comment]
@shichuanq 
For face recognizer from opencv_classes2413.dll the system used Mat, I assumed.

> 	ICLASS_API void __stdcall FaceRecognizerTrain(FaceRecognizer* e, int n, IplImage** scr, int* lab)
> 	{
> 		vector<Mat> images;
> 		vector<int> labels;
> 		for (int i = 0; i < n; i++)
> 		{
> 			images.push_back(Mat(scr[i])); 
> 			labels.push_back(lab[i]);
> 		}
> 		e->train(images, labels);
> 	};
