### ISSUE TITLE
About Delphi 10.2 Opcv cvload E06D7363 Error

### ISSUE THREAD

**Issue by kingdjf** [Laex/Delphi-OpenCV#103]
When i click button system show a Error E06D7363. 
This is my code:

Const
  cascade_name: pCVChar = 'D:\resource\facedetectxml\haarcascade_frontalface_alt.xml'; // cascade file
var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.Button1Click(Sender: TObject);
var
  cascade: pCvHaarClassifierCascade;
  storage: pCvMemStorage;
begin
  cascade := cvLoad(cascade_name, nil, nil, nil);
  if Assigned(cascade) then showmessage('ok');
end;

**Comment by kingdjf** [comment]
![image](https://user-images.githubusercontent.com/20849778/35557667-bf791c62-05e0-11e8-99cc-4d888428203e.png)

**Comment by blaisexen** [comment]
This line was the issue:
change from:
cascade_name: pCVChar = 'D:\resource\facedetectxml\haarcascade_frontalface_alt.xml'; // cascade file
change to:
cascade_name: AnsiString = 'D:\resource\facedetectxml\haarcascade_frontalface_alt.xml'; // cascade file

:dancer:

**Comment by blaisexen** [comment]
and if your looking for Delphi face detection, here's my link:
https://sourceforge.net/u/blaisexen/profile/

**Comment by kingdjf** [comment]
Thank you for your help!   when i change pCVChar to AnsiString and use CVLOAD(PCVChar(@cascade_name[1]),nil,nil,nil) method, but CVLOAD still return nil。

BTW:your project running verygood. Now i need contrast your project  to find my error.
![image](https://user-images.githubusercontent.com/20849778/35602480-651ff54a-0673-11e8-8305-50fc288be6e2.png)

**Comment by kingdjf** [comment]
i create a new project copy your project code to my project look at the picture.
my project onlye have a button and a buttonclick.when i click button the cvload return nil.why?
![image](https://user-images.githubusercontent.com/20849778/35610898-194cc7d0-069e-11e8-9cbf-6c20f8aedad1.png)
unit Unit1;

interface

uses
  ocv.imgproc_c,
  ocv.imgproc.types_c,
  ocv.core.types_c,
  ocv.core_c,
  ocv.highgui_c,
  ocv.objdetect_c,
  ocv.utils,
  ocv.cls.contrib,
  ocv.legacy,

  Windows,
  Messages,
  SysUtils,
  Variants,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  ExtCtrls,
  StdCtrls;

type
  TForm1 = class(TForm)
    Button1: TButton;
    procedure Button1Click(Sender: TObject);
  private
    { Private declarations }
    SessionEnding: Boolean;
    procedure WMQueryEndSession(var Message: TMessage); message WM_QUERYENDSESSION;
  public
    { Public declarations }
  end;

var
  Form1: TForm1;
  FaceCascadeFile: AnsiString = 'face.xml';
  FaceCascade: pCvHaarClassifierCascade = nil;

implementation

{$R *.dfm}

procedure TForm1.Button1Click(Sender: TObject);
begin
    FaceCascade := cvLoad(pCVChar(@FaceCascadeFile[1]), nil, nil, nil);
    if not Assigned(FaceCascade) then
    begin
      ShowMessage('ERROR: Could not load(face.xml).');
      Halt;
    end;
end;

procedure TForm1.WMQueryEndSession(var Message: TMessage);
begin
  SessionEnding := True;
  Message.Result := 1;
end;

end.

**Comment by blaisexen** [comment]
hi,
I tried other version of opencv, still error comes out.

I think it's a bug NOT from opencv, but it's a wrapper code of pascal.
A global variable assigned that if that variable is not seen before or after the cvload creates an error.

I think you should report this @Laex  but I hope he will noticed this post.

try to make the code larger, use some code that might trigger using cvload or classifier

Good Luck

**Comment by blaisexen** [comment]
here's my though,

program FaceDetect;
{$APPTYPE CONSOLE}
{$R *.res}
uses
  ocv.core.types_c,
  ocv.core_c,
  ocv.highgui_c,
  ocv.objdetect_c,
  ocv.imgproc_c,
  ocv.imgproc.types_c,
  ocv.utils;
Const
  cascade_name: pCVChar ='face.xml';

Var
  capture: pCvCapture = nil;
  DUMMY_objects: pCvSeq = nil;
  cascade: pCvHaarClassifierCascade;
  storage: pCvMemStorage;
  gray: pIplImage;

begin

    cascade := cvLoad(cascade_name, nil, nil, nil);
    if Assigned(cascade) then
      Writeln('LOADED : ', cascade_name)
    else
    begin
      Writeln('ERROR: Could not load classifier cascade : ', cascade_name);
      Halt(1);
    end;

    if not Assigned(capture) then Halt(1);

    //IF YOU REMOVE THIS LINES BELOW,, error....out....
    DUMMY_objects := cvHaarDetectObjects(gray, cascade, storage, 1.2, 4, CV_HAAR_DO_CANNY_PRUNING, cvSize(30, 30), cvSize(0, 0));

    ///So, make use of the code that would grow larger...
    ///that uses every sources you have....

end.

Good Luck

**Comment by kingdjf** [comment]
I use your method,new a project,this picture is my project
![image](https://user-images.githubusercontent.com/20849778/35667035-1f7d0376-0767-11e8-8375-1abe6fc48bdf.png)
when i running i get this message!
![image](https://user-images.githubusercontent.com/20849778/35667018-1510a924-0767-11e8-949a-4b81cab572db.png)

**Comment by blaisexen** [comment]
your doing wrong, please read word by word my last comment.
Good Luck.

**Comment by HuguesDug** [comment]
I think that as cvChar is a null terminated string, shouldn't you as +#0 as a last position of your chain ?

Instead of 
Const
  cascade_name: pCVChar ='face.xml';

Try
Const
  cascade_name: pCVChar ='face.xml'+#0;

By the way, you should reroute opencv exceptions in your pascal code to be able to read the messages with a clear string.

Here a piece of code to do so:

function cvDelphiErrorHandler(status: Integer; const func_name: PCvChar; const err_msg: PCvChar;
  const file_name: PCvChar; line: Integer; user_data: pointer): Integer; cdecl;
const
  mrAbort = 3;
  mrIgnore = 5;
var
  errMsg: string;
begin
  errMsg := err_msg;
  if errMsg = '' then
  begin
    errMsg := cvErrorStr(status);
  end;

  begin
    result := 0;
    // reset error status avoiding a cascade of subsequent errors
    cvSetErrStatus(0);
  end;
  Raise Exception.CreateFmt('OpenCV error: in file <<%s>> function <<%s>> line <<%d>> - %s',
    [file_name, func_name, line, errMsg]);
end;

procedure TForm1.FormCreate(Sender: TObject);
begin
  ReportMemoryLeaksOnShutdown:=true;

  cvRedirectError(cvDelphiErrorHandler);

end;

**Comment by blaisexen** [comment]
> Const cascade_name: pCVChar ='face.xml'+#0;
Error?

**Comment by blaisexen** [comment]
> begin
>       ReportMemoryLeaksOnShutdown:=true;
>       cvRedirectError(cvDelphiErrorHandler);
yeah, add that line, it helps I think.
from my side it say's a memory leak

**Comment by blaisexen** [comment]
Hi @Lesnik351 I think @HuguesDug,already answered this issue, I also test it, it was proven solved, at least from my side.

Just follow the comments and you'll used at it.
