### ISSUE TITLE
Freeze when change frames size

### ISSUE THREAD

**Issue by cristiano070** [Laex/Delphi-OpenCV#104]
Some bugs are related to changes on video frames size when in nested operations.
Eg. Cropping and AbsDiff operations will freeze when crops.

Is possible to round this discarding previous frame before crop operations or checking size changes when DoTransform.

To discard, you can include the following procedure at ocv.comp.ImageOperation:
procedure TocvAbsDiff.DiscardPrevFrame;
begin
   FPrevFrame := nil;
end;

Use:
  TocvAbsDiff(ocvDiff.Operation).DiscardPrevFrame;
  TocvCropOperation(ocvCrop.Operation).CropRect := rRect;

**Comment by Laex** [comment]
Accepted...
Not understood: TocvCropOperation(ocvCrop.Operation).CropRect := rRect;
