### ISSUE TITLE
File missing in branch

### ISSUE THREAD

**Issue by ertankucukoglu** [Laex/Delphi-OpenCV#109]
Hello,

Resources are missing 24042013145540.avi file for CarNumDetect demo.

Thanks.

**Comment by Laex** [comment]
I do not have this file. Apply directly to the Mikhail Grigorev (email: sleuthhound@gmail.com)

**Comment by blaisexen** [comment]
here's the demo your looking,
https://github.com/Laex/Delphi-OpenCV/tree/master/samples/MultiDemo/CarNumDetect

**Comment by Laex** [comment]
Maybe.
I just said that I do not have this file
