### ISSUE TITLE
File not found: libversion.inc

### ISSUE THREAD

**Issue by silvioprog** [Laex/Delphi-OpenCV#110]
Hi.

This error was raised compiling the CheckCVDep. Could you shared this the file `libversion.inc`?

Thank you!

**Comment by Laex** [comment]
libversion.inc is part of the "FFmpeg Delphi / Pascal Headers and Examples" located in the "Delphi-OpenCV\source\ffmpeg\" repository.
Download it at http://www.delphiffmpeg.com/download/ffmpeg-delphi-pascal-headers-3.4.2.zip

**Comment by silvioprog** [comment]
Thank you very much @Laex ! :+1:
