### ISSUE TITLE
Cant Install dclCommonOpenCV240.bpl

### ISSUE THREAD

**Issue by 3ddark** [Laex/Delphi-OpenCV#111]
![screenshot_1](https://user-images.githubusercontent.com/5977787/47412438-74c44c80-d774-11e8-870b-6d3bb386f23f.png)
Build, Compile **successfully** completed. then click Install but see this message. 

Can't load package C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win32\dclCommonOpenCV240.bpl.
%1 **not a valid win32 application**

I'm Followed the that Instruction
**https://github.com/Laex/Delphi-OpenCV#how-to-install**

**Comment by Laex** [comment]
https://github.com/Laex/Delphi-OpenCV#verify-that-the-environment-is-configured-correctly
