### ISSUE TITLE
Can not install dclFFMSource250.bpl,Why?

### ISSUE THREAD

**Issue by sxbug** [Laex/Delphi-OpenCV#112]
When I installed dclFFMSource250.bpl,the error msg displayed: can not load package, The specified module could not be found.(Win 10 64Bit, Delphi 10.2.3)

Verifying OpenCV dependencies checked:
------- Verifying Microsoft DLL -------
OK
------- OpenCV DLL -------
OK
------- Delphi-OpenCV classes DLL -------
OK
------- FFMPEG DLL -------
OK
------- SDL DLL -------
OK

How can I do?

Thanks

**Comment by Laex** [comment]
This has never happened and here again ...
Problem solved?

**Comment by sxbug** [comment]
No solved.
I can not install it anyway.

**Comment by Laex** [comment]
Microsoft DLLs, OpenCV DLLs,  Delphi-OpenCV classes DLLs, FFMPEG DLLs,  SDL DLLs should be available to any program through the system variable PATH or located in catalogs according to the instructions - https://github.com/Laex/Delphi-OpenCV#requirements

Perhaps they are only available to the CheckCVDep.exe.

**Comment by zadehalex** [comment]
In my case, I got some error, but fixed.

environment: win8.1, 32bits,delphi xe10.2.3

error1:  ocv.comp.FFMSource.pas - CODEC_CAP_TRUNCATED not define
  if (pCodec^.capabilities and CODEC_CAP_TRUNCATED) = 0 then
      pCodecCtx^.flags := pCodecCtx^.flags or CODEC_FLAG_TRUNCATED; (* we dont send complete frames *)
fixed:  rename CODEC_CAP_TRUNCATED to AV_CODEC_CAP_TRUNCATED	  

error2: 
dclFFMSourceXXX.dpk can't be istall, need avutil-56.dll
FFMPEG 3.4.2 only have avutil-55.dll

fixed: install both FFMPEG 3.4.2 and 4.0.0

**Comment by zadehalex** [comment]
It can be download here:  FFMPEG 4.0.0
https://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-4.0-win32-shared.zip
https://ffmpeg.zeranoe.com/builds/

cc to Laex, thank you and your team member, the project is real cool! ( I had used c++ to develop opencv code, it is real not convenience than using delphi....)

**Comment by sxbug** [comment]
Yes. After I copied  ffmpeg 4.0 's dll to sysWOW64 , I can install dclFFMSource250.bpl

Thanks
