### ISSUE TITLE
How to use Convex Hull3D function?

### ISSUE THREAD

**Issue by sxbug** [Laex/Delphi-OpenCV#113]
I had a lot of points(xyz Axis),I want to use OpenCV to build a mesh by these points.
I want to use OpenCV 's Convex Hull function, but I can not know how to do.

Can you help me? Thanks

**Comment by Laex** [comment]
The function "convexHull" uses c ++ classes. Therefore, it was not translated into Object Pascal.
https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga014b28e56cb8854c0de4a211cb2be656

**Comment by sxbug** [comment]
Can I do this function  by calling the DLL files? Is there any other way to turn many points to a mesh in Delphi? Thank you

**Comment by Laex** [comment]
1. You can write a small dll in C ++ that translates the call from Delphi to the call (inside the dll) of the function convexHull
2. You can open the source code of the convexHull function and translate it into Object Pascal code
3. You can take the original article (Sklansky, J., Finding the Convex Hull of a Simple Polygon. PRL 1 $ number, pp 79-83 (1982)) and write the code yourself

Variants are given in order of increasing complexity.
