### ISSUE TITLE
Access Violation for video from 2 cameras 

### ISSUE THREAD

**Issue by StankevichSL** [Laex/Delphi-OpenCV#114]
Good day! 
It's my first project with openCV and I faced with a error of memory access. There are two cameras, web and IP. The image is obtained through the Tocvcamerasource component(s) and TocvIPCamSource and output to the corresponding Tocvviewfmx components. The components of the image output on the form are arranged so that one overlaps the other.
Photo of components arrangement (https://cloud.mail.ru/public/DvXQ/QbeARbACN)
When you start the program runs from 0.5-10 seconds, and then crashes with an error
Link to the photo with an error(https://cloud.mail.ru/public/LAcA/h8FLJ5fUe)
If you go on the chain first pulls in the System.pas
`@FwdLoop:
        FILD    QWORD PTR [EAX+ECX]`
Next, in procedure TocvViewFMX.The Paint in the unit ocv.comp.ViewFMX
`    IPLImageToFMXBitmap(FImage.IpImage, BackBuffer);`
I tried to spread the elements of the video display to different angles, so that they do not intersect, everything works stably. 
It is logical to assume that the problem is hidden in the rendering.
My thoughts on the work of the program remain on the verge of mysticism and dancing with a tambourine. Any idea where to dig? The source code will be provide on demand.

**Comment by Laex** [comment]
Fixed [#114]
