### ISSUE TITLE
Bug in Tocvcamerasource .onimage

### ISSUE THREAD

**Issue by JeanYvesJonet** [Laex/Delphi-OpenCV#115]
Hello,
when you are triggering camera ,  if you disconnected it, it's impossible to reconnect it. You need to restart delphi application.  (all threads are frozen)
But if you are sending frames in continous it's possible to disconnect camera en re-connect on line without any problem. 
I think it's a problem into the thread of frame capture, it is waiting for a frame capture ... and stay blocked.
Thank you for your help.
Best regards

**Comment by JeanYvesJonet** [comment]
Hello,
no changement. I try it but after "Device Unplugged"  it's impossible to restart camera without stop application. Perhaps i don't execute good code to reconnect it ?
Best regards.

**Comment by HuguesDug** [comment]
Hello Laex,

I think it has to see with the handling of error when you use cvgrabeframe inside the ThreadExecute. You have a try finally, but in case you have an exception, you do not "manage" the error, then the thread loops permanently.

**Comment by Laex** [comment]
This bug was fixed in OpenCV 3.0 (https://github.com/opencv/opencv/issues/5746)

**Comment by HuguesDug** [comment]
Possible to use your wrapper with OpenCV 3.0 ?
