### ISSUE TITLE
Access Viloation using ocvViewFMX 

### ISSUE THREAD

**Issue by jeongminBaek** [Laex/Delphi-OpenCV#116]
AccessViolation occurs while playing video when using ocvViewFMX1.
The same phenomenon occurs when one image or several images are reproduced.
It appears to be issued when using ocvViewFMX1, not IPCam Source Component.

**Comment by Laex** [comment]
I could not reproduce the error.
Give an example

**Comment by jeongminBaek** [comment]
![image](https://user-images.githubusercontent.com/3453489/54028109-3ab98b80-41e7-11e9-945e-e3309977076c.png)
![image](https://user-images.githubusercontent.com/3453489/54028126-4907a780-41e7-11e9-99fc-1f60bc8509ef.png)
![image](https://user-images.githubusercontent.com/3453489/54028130-50c74c00-41e7-11e9-9ccb-c2c0b68aedb2.png)

[[Click to Watch as a video](http://www.koreapr.co.kr/ocv/ocvFMXViewer_Resize_Error.mp4)]
