### ISSUE TITLE
Can not install dclFFMSource260.bpl,Why?

### ISSUE THREAD

**Issue by golddmiry** [Laex/Delphi-OpenCV#126]
http://prntscr.com/pbf77h

**Comment by Laex** [comment]
Use Delphi-FFMPEG

**Comment by golddmiry** [comment]
> 
> 
> Use Delphi-FFMPEG

Что?
Последние headers(ffmpeg-delphi-pascal-headers-4.1.4.zip) отсюда - http://www.delphiffmpeg.com/headers/ я засунул в папку c:\Program Files\Embarcadero\Delphi-OpenCV-master\source\Delphi-FFMPEG\source\. До этого вообще писал, что avicodec not found

**Comment by golddmiry** [comment]
Хотя.
------- Verifying Microsoft DLL -------
concrt140.dll - ok
concrt140d.dll - ok
msvcp140.dll - ok
msvcp140d.dll - ok
ucrtbase.dll - ok
ucrtbased.dll - ok
vcruntime140.dll - ok
vcruntime140d.dll - ok
OK
------- OpenCV DLL -------
opencv_calib3d2413.dll - ok
opencv_calib3d2413d.dll - ok
opencv_contrib2413.dll - ok
opencv_contrib2413d.dll - ok
opencv_core2413.dll - ok
opencv_core2413d.dll - ok
opencv_features2d2413.dll - ok
opencv_features2d2413d.dll - ok
opencv_flann2413.dll - ok
opencv_flann2413d.dll - ok
opencv_gpu2413.dll - ok
opencv_gpu2413d.dll - ok
opencv_highgui2413.dll - ok
opencv_highgui2413d.dll - ok
opencv_imgproc2413.dll - ok
opencv_imgproc2413d.dll - ok
opencv_legacy2413.dll - ok
opencv_legacy2413d.dll - ok
opencv_ml2413.dll - ok
opencv_ml2413d.dll - ok
opencv_nonfree2413.dll - ok
opencv_nonfree2413d.dll - ok
opencv_objdetect2413.dll - ok
opencv_objdetect2413d.dll - ok
opencv_ocl2413.dll - ok
opencv_ocl2413d.dll - ok
opencv_photo2413.dll - ok
opencv_photo2413d.dll - ok
opencv_stitching2413.dll - ok
opencv_stitching2413d.dll - ok
opencv_superres2413.dll - ok
opencv_superres2413d.dll - ok
opencv_video2413.dll - ok
opencv_video2413d.dll - ok
opencv_videostab2413.dll - ok
opencv_videostab2413d.dll - ok
opencv_ffmpeg2413.dll - ok
opencv_ffmpeg2413d.dll - ok
OK
------- Delphi-OpenCV classes DLL -------
opencv_classes2413.dll - ok
opencv_classes2413d.dll - ok
OK
------- FFMPEG DLL -------
avcodec-58.dll.dll - ok
avdevice-58.dll.dll - ok
avfilter-7.dll.dll - ok
avformat-58.dll.dll - ok
avutil-56.dll.dll - ok
swresample-3.dll.dll - ok
swscale-5.dll.dll - ok
OK
------- SDL DLL -------
SDL.dll - ok
SDL2.dll - ok
OK

**Comment by Laex** [comment]
Теперь в составе проекта используется собственная трансляция FFMPEG (https://github.com/Laex/Delphi-FFMPEG.git)
В репозитарии это задано как субмодуль (https://github.com/Laex/Delphi-OpenCV/tree/master/source/Delphi-FFMPEG/)
Теперь надо скачивать https://github.com/Laex/Delphi-FFMPEG (в любое удобное место) и прописать пути к "Delphi-FFMPEG/source/"

Трансляция Delphi-FFMPEG более компактная, названия структур соответствует оригинальным названиям FFMPEG, некоторые функции удобней использовать, ну и соответствует последней версии FFMPEG.
