### ISSUE TITLE
Please, separate them into Runtime and DesignTime Package

### ISSUE THREAD

**Issue by linces** [Laex/Delphi-OpenCV#127]
Please, separate them into Runtime and DesignTime Package.

Its very annoying and dificulte to make 32 bit and 64 bit for our applications, even install into 64 bit its impossible, this is a hard problem into this project.

Looks like this is abandoned

**Comment by blaisexen** [comment]
Hi,
I'm not sure if I understand your needs, but for me I have made applications out from the packages of Delphi-OpenCv.

Try separating them, or like I did from this post,
https://sourceforge.net/projects/delphi-opencv-face-detection/

Good Luck

**Comment by Laex** [comment]
For testing... (last commit)
