### ISSUE TITLE
ocv.comp.proc.pas Undeclared identifier: 'CascadeRecourse'

### ISSUE THREAD

**Issue by boomsya** [Laex/Delphi-OpenCV#128]
увы нигде нет массива CascadeRecourse
поиск по исходнику ничего не дал

по этой причине не компонент нет возможности установить

**Comment by boomsya** [comment]
хм. оказывается он есть в haarcascade.inc
было закоменчено 
{$I haarcascade.inc}
{$R haarcascade.res haarcascade.rc}
{$R haarcascade.res}

всё собирается. Сори за беспокойство.

**Comment by boomsya** [comment]
увы не устанавливается компонент. Хотя по факту файл создается.
Даже вручную установка не помогает. Аналогично ругается.
![111](https://user-images.githubusercontent.com/8008462/74333037-c9436f00-4d9f-11ea-8a6d-9d7e70b8e776.jpg)

**Comment by Laex** [comment]
Не может найти opencv dll
Смотри readme.md
DLL-ки должны быть доступны в PATH (прописаны в путях или размещены в каталогах, указанных в readme.md)

**Comment by boomsya** [comment]
понял, спасибо. Попробую.

**Comment by boomsya** [comment]
всё работает, спасибо за подсказку. Не знал, что могут быть такие траблы из-за отсутствия dll в path
