### ISSUE TITLE
Can We Update To Newer version ex to 3.0 or 4.0 ?

### ISSUE THREAD

**Issue by miftakhulterang** [Laex/Delphi-OpenCV#136]
this project on version 2.x,  Can We Update To Newer version ex to 3.0 or 4.0 ?

**Comment by HuguesDug** [comment]
Hello.

Question asked in bugtracker #35 

You cannot use the DLL from OpenCv 3.0 or 4.0 directly with this wrapper. 
C interface was discarded by OpenCV team. They use only C++, what is not "nativelly" compatible with Delphi.

Having tryed to overcome the problem, I saw numerous problems appearing, in particular the problem of the strings that have moved from ANSI to Unicode, it seams. Si read and write of files does not work.

Authors of this wonderfull wrapper said some month ago that will try to introduce the 3.0 version in the future, but they did not disclose timeline for that.

Last, if you see another lib that is compatible with 3.0 or 4.0, please, post a comment here.
