### ISSUE TITLE
Merge modifications for Lazarus - FPC compiler to the current branch

### ISSUE THREAD

**Issue by HuguesDug** [Laex/Delphi-OpenCV#137]
Hello,

I found this excellent work inside github : a port of your wrapper to Lazarus/FPC compiler.
https://github.com/t-edson/LazarusOpenCV

I suggest you include the modifications in your own code with compiler switches so all the community can benefit from the updates you regularly make.

Thanks

**Comment by Laex** [comment]
Yes, it's a good idea. But I think it's better to spend time developing a wrapper for OpenCV 4.5.1

**Comment by Laex** [comment]
https://github.com/Laex/Delphi-OpenCV-Class
