### ISSUE TITLE
Support vector machine (SVM) support

### ISSUE THREAD

**Issue by boomsya** [Laex/Delphi-OpenCV#138]
Access OpenCV headers and samples for #Delphi which contain 2D and 3D feature toolkits, Egomotion estimation, Facial recognition system, Gesture recognition, ....**Support vector machine (SVM)**.

So i can`t found demo or src with SVM. 
no demo, no type declaration in src :(

**Comment by Laex** [comment]
Vector machine appeared in OpenCV 3.4.
This project supports OpenCV 2.4.13

**Comment by boomsya** [comment]
:( thanks
is it possible for this project to be updated to 3.4 in the future?
