### ISSUE TITLE
can not install to delphi 11.1

### ISSUE THREAD

**Issue by artdelphi** [Laex/Delphi-OpenCV#150]
i can't install to delphi 11.1
unit ocv.utils;
[dcc32 Fatal Error] ocv.utils.pas(64): F2613 Unit 'Graphics' not found.

**Comment by Laex** [comment]
Run "InitDelphiFFMPEG.cmd" to update DelphiFFMPEG("Delphi-OpenCV\Delphi-FFMPEG\") and JEDI ("Delphi-OpenCV\jedi\") modules.
