### ISSUE TITLE
How to install in Delphi 10.4 ? Please

### ISSUE THREAD

**Issue by Kristofer1212** [Laex/Delphi-OpenCV#151]
Hello guys, my windows 10 is 64bits.

I'm trying to instal OpenCV in Delphi 10.4 . 

I followed all the steps, and the dll's are in the right place. But when i try to check i'm getting too many errors.

I'm trying too Install the components. Some of them i can build, but cannot install. Other i can.

Plaese how can i proceed ? Thanks.

![image](https://user-images.githubusercontent.com/68922219/174449881-165b744f-3ba8-43bf-8cbc-5bc8368c8a0a.png)

**Comment by Laex** [comment]
dll must be in the same directory as the program being run or in a directory that is included in the system PATH variable
