### ISSUE TITLE
How to install in Delphi 10.4. Followed all steps

### ISSUE THREAD

**Issue by Kristofer1212** [Laex/Delphi-OpenCV#152]
Hello again guys. I'm still stucked :''(. I followed all the steps, added all, followed the git, runned de init ffmpeg, puted the dlls.

The ONLY step i i didn't understood was Dynamic library. When can i find that ?

Please help me !! Sorry poor english. Thanks !!!

![image](https://user-images.githubusercontent.com/68922219/174449872-4a54b163-386a-49b9-8ea0-e36b4d1e5c7e.png)

**Comment by Laex** [comment]
dll must be in the same directory as the program being run or in a directory that is included in the system PATH variable
