### ISSUE TITLE
delphi 10.2 install error

### ISSUE THREAD

**Issue by promise1999hubo** [Laex/Delphi-OpenCV#154]
[dcc32 Fatal Error] OpenCV.inc(1): F1026 File not found: 'jedi.inc'

**Comment by promise1999hubo** [comment]
when i delete  {$i jedi.inc} ,then complie  ,
[dcc32 Error] ocv.core_c.pas(601): E2065 Unsatisfied forward or external declaration: 'cvGetSize'
[dcc32 Fatal Error] ocv.core.types_c.pas(2397): F2063 Could not compile used unit 'ocv.core_c.pas'

**Comment by promise1999hubo** [comment]
s

**Comment by Laex** [comment]
Run InitDelphiFFMPEG.cmd
