### ISSUE TITLE
Missing uResourcePaths.pas

### ISSUE THREAD

**Issue by dalibor31** [Laex/Delphi-OpenCV#156]
[dcc32 Fatal Error] FaceRecognizer.dpr(18): F1026 File not found: '..\..\..\source\utils\uResourcePaths.pas'

**Comment by Laex** [comment]
File "uResourcePaths.pas" moved to "\Delphi-OpenCV\resource\uResourcePaths.pas".
Sorry for inconvenience.

**Comment by Laex** [comment]
Classes are no longer supported here.
See "https://github.com/Laex/Delphi-OpenCV-Class"
