### ISSUE TITLE
there are error when install opencv on xe7

### ISSUE THREAD

**Issue by asdk2006** [Laex/Delphi-OpenCV#29]
![error](https://cloud.githubusercontent.com/assets/10379485/5602037/d4c983ee-9339-11e4-80fd-5cd62894415e.jpg)

**Comment by Laex** [comment]
See readme
* Requires installed Visual C++ redistributable for Visual Studio 2013 (http://www.microsoft.com/ru-ru/download/details.aspx?id=40784)   
* Dynamic OpenCV library is not included in the repository!
* Dynamic library OpenCV need to download from http://opencv.org/downloads.html
* Shared library FFMPEG for Windows can be downloaded from http://ffmpeg.zeranoe.com/builds/

Some examples (FFMPEG) required SDL 2.0 and SDL 1.2

**Comment by asdk2006** [comment]
ok for Dynamic library OpenCV  i install it and wich folder contain the opencv_*.dll

**Comment by asdk2006** [comment]
can you make video how to install opencv on delphi

**Comment by Laex** [comment]
Do not forget to add to your PATH variable path to the library "opencv_*.dll" and FFMPEG

**Comment by asdk2006** [comment]
thank you for every thing i do all steps on delphi xe7
 but still show the error in the first post can you help me please

**Comment by asdk2006** [comment]
if you tell me just the way of define the path of opencv and ffmpeg

**Comment by asdk2006** [comment]
not work i try all ways in xe7 but stell show me same message in the first post
