### ISSUE TITLE
FeatureDetector

### ISSUE THREAD

**Issue by Stasev** [Laex/Delphi-OpenCV#30]
Здравствуйте, очень интересуют Ваши планы по обертке для FeatureDetector.
Спасибо.

**Comment by Laex** [comment]
Планируется....
Все зависит от свободного времени

**Comment by Stasev** [comment]
Уж очень хочется пощупать этот ocv.features2d.pas...
Может можно как-то ускорить этот процесс. 
Donate или еще как?
Извиняюсь: не знаю здешних правил.

**Comment by Laex** [comment]
features2d - это сплошные C++ классы.
Написание врапперов для них, мягко скажем, не простое занятие.
Могу попробовать в выходные (24-25.01)
Правил нет (это ж открытый проект).
А Donate - оно всегда способствует (мотивирует) ;)

**Comment by Stasev** [comment]
А данные для Donate где подсмотреть?
Золотых гор не обещаю, но пару рублей найду :)

**Comment by Laex** [comment]
Добавил кнопку

**Comment by Stasev** [comment]
[ Могу попробовать в выходные (24-25.01) ]

- Было бы здорово!!!
Спасибо.

зы
--
кнопку нашел не сразу :)
