### ISSUE TITLE
error in Delphi-OpenCV/samples/LibDemo/cvMatchShapes/cv_MatchShapes.dpr

### ISSUE THREAD

**Issue by Stasev** [Laex/Delphi-OpenCV#31]
В примерах cv_MatchShapes.dpr и cv_MatchShapes2.dpr 
Delphi XE3 вылетает с эксепшеном.
Я так понял, дело в storage, для шаблона надо отдельный экземпляр storage создавать.
А то получается:
- берем основные контура, поработали
- почистили хранилище
- берем контура шаблона, поработали
- возвращаемся к основным, а там данные контуров шаблона... Exeption

**Comment by Laex** [comment]
Да, все правильно
