### ISSUE TITLE
cvLoadLatentSvmDetector

### ISSUE THREAD

**Issue by Stasev** [Laex/Delphi-OpenCV#32]
Добрый день, 
может в примере ошибка потому что в "Delphi-OpenCV/source/ocv.objdetect_c.pas"
способы вызова для "Latent SVM Object Detection functions" указаны 
как stdcall, а не cdecl?
Я в обертках не силен но судя по вики, это вполне реально:
"Во всех соглашениях (кроме cdecl) подпрограмма обязана обеспечить восстановление перед возвратом значений сегментных регистров процессора ..."

**Comment by Laex** [comment]
Да, моя ошибка...
