### ISSUE TITLE
Installation in XE6 issue

### ISSUE THREAD

**Issue by Miamy** [Laex/Delphi-OpenCV#34]
Hi. I have experienced the same issue that spiders06 described in https://github.com/Laex/Delphi-OpenCV/issues/16.

I have Win 7 64 bit, Delphi XE6 Update1. I installed opencv 2.4.9, append it's binaries folder and FFMPEG folder in system path, installed Visual C++ redistributable for VS 2013 and append needed folders in Delphi. 

When I tried to install dcl**CV200 packages, I obtained an error 
![image](https://cloud.githubusercontent.com/assets/3795504/6675687/c6ab7df4-cc3b-11e4-8665-aa10242e8f79.png).

I tried different opencv and  VC++ redistributables, tried to append Win64 target in Delphi, but cannot install packages anyway.

So can you kindly provided me with information:
1) which binaries should be seen in system path (in opencv installation folder I have x64 and x86 folders and vc10, vc11,vc12 subfolders in every one)?
2) which VC++ redistributables binaries should be installed - x64 or x86?
3) any other known issues, which can prevent packages installation?

Thank you for a help.

**Comment by Laex** [comment]
----------------------- Necessary files -----------------------
1. Visual C ++ redistributable for Visual Studio 2013
    (1) 32-bit in the "Delphi-OpenCV\redist\VC2013x86\"
    (2) 64-bit in the "Delphi-OpenCV \ redist \ VC2013x64 \"
       Release (* 120.dll)
         msvcp120.dll, msvcr120.dll
       Debug (* 120d.dll)
         msvcp120d.dll, msvcr120d.dll
2. FFMPEG (http://ffmpeg.zeranoe.com/builds/)
    (3) FFmpeg 32-bit Shared
    (4) FFmpeg 64-bit Shared
       Release and Debug
         avcodec-56.dll, avdevice-56.dll, avfilter-5.dll, avformat-56.dll, avutil-54.dll, postproc-53.dll,
         swresample-1.dll, swscale-3.dll
3. OpenCV 2.4.9 
    (Https://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.9/opencv-2.4.9.exe/download)
    After installing OpenCV:
    (5) 32-bit in the C:\OpenCV\build\x86\vc12\bin\
    (6) 64-bit in the C:\OpenCV\build\x64\vc12\bin\
       Release (* 249.dll)
         opencv_calib3d249.dll, opencv_contrib249.dll, opencv_core249.dll,
         opencv_features2d249.dll, opencv_ffmpeg249.dll, opencv_flann249d.dll, opencv_gpu249d.dll,
         opencv_flann249.dll, opencv_gpu249.dll, opencv_highgui249.dll, opencv_imgproc249.dll,
         opencv_legacy249.dll, opencv_ml249. dll, opencv_nonfree249.dll, opencv_objdetect249.dll,
         opencv_ocl249.dll, opencv_photo249.dll, opencv_stitching249.dll, opencv_superres249.dll,
         opencv_video249.dll, opencv_videostab249.dll
       Debug (* 249d.dll)
         opencv_calib3d249d.dll, opencv_contrib249d.dll, opencv_core249d.dll,
         opencv_features2d249d.dll, opencv_highgui249d.dll, opencv_imgproc249d.dll,
         opencv_legacy249d.dll, opencv_ml249d.dll, opencv_nonfree249d.dll,
         opencv_objdetect249d.dll, opencv_ocl249d.dll, opencv_photo249d.dll,
         opencv_stitching249d.dll, opencv_superres249d.dll, opencv_video249d.dll,
         opencv_videostab249d.dll

----------------------- Copying files -----------------------
OS Windows 64-bit
   Target platform 64-bit
         (2), (4), (6) -> "C:\Windows\System32\"
   Target platform 32-bit
         (1), (3), (5) -> "C:\Windows\SysWOW64\"

OS Windows 32-bit
   Target platform 32-bit
         (1), (3), (5) -> "C:\Windows\System32\"

**Comment by Miamy** [comment]
Yes, after executing this sequence packages were installed. Thank you!
