### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by zirill** [Laex/Delphi-OpenCV#36]
Здравствуйте, что-то не могу разобраться, расчеты ведутся на cpu или gpu?
Если на cpu то как подключить использование gpu (CUDA).

**Comment by Laex** [comment]
cpu
Расчеты на gpu ведутся через классы С++
Разработка оберткок над классами С++ начата, но очень трудоемка.
Времени пока не хватает

**Comment by zirill** [comment]
Спасибо за скорый ответ, а примерно когда ожидать этого обновления?

**Comment by Laex** [comment]
Думаю, не раньше начала лета

**Comment by ndv87** [comment]
Обертка для OpenCL уже давно есть на Delphi. Я пользовался в своем проекте вот этим https://code.google.com/archive/p/delphi-opencl/downloads
