### ISSUE TITLE
Component-->Image operation-->MotionDetect

### ISSUE THREAD

**Issue by Caine69** [Laex/Delphi-OpenCV#38]
Hi!
I’ve tried to use Your component with option MotionDetect in my application and I’ve noticed that after a few moments camera display and application are freezing. So, I’ve used Your sample application cCameraCapture in ComponentsDemo and problem has appeared too. I’ve added ReportMemoryLeaksOnShutdown to code and I’ve noticed that there are huge memory leaks in MotionDetect procedure. I’ve tried to cleanup used variables in function TocvMotionDetect.DoTransform in ocv.comp.ImageOperation.pas but it hasn’t fixed the problem. Could you take care about this bug? Thanks! 
![memory leak](https://cloud.githubusercontent.com/assets/11923947/9461299/dd493276-4b0d-11e5-9be2-fcda2e60d142.PNG)

**Comment by Laex** [comment]
Please send the source code.
In the example cCameraCapture no memory leaks.

**Comment by Caine69** [comment]
Thank you for fast response! I've sent you the source code in attachement in e-mail.
