### ISSUE TITLE
I try to get  findCirclesGridDefault to work in delphi.

### ISSUE THREAD

**Issue by BenediktS** [Laex/Delphi-OpenCV#41]
Hello, 

i tried to get the circle calibration to work.
In the c header  files there are the following lines:

```
enum { CALIB_CB_SYMMETRIC_GRID = 1, CALIB_CB_ASYMMETRIC_GRID = 2,
       CALIB_CB_CLUSTERING = 4 };

//! finds circles' grid pattern of the specified size in the image
CV_EXPORTS_W bool findCirclesGrid( InputArray image, Size patternSize,
                                 OutputArray centers, int flags=CALIB_CB_SYMMETRIC_GRID,
                                 const Ptr<FeatureDetector> &blobDetector = new SimpleBlobDetector());

//! the deprecated function. Use findCirclesGrid() instead of it.
CV_EXPORTS_W bool findCirclesGridDefault( InputArray image, Size patternSize,
                                          OutputArray centers, int flags=CALIB_CB_SYMMETRIC_GRID );
```

I tried to get them into delphi with these lines in the ocv.calib3d_c.pas :

```
const
CV_CALIB_CB_SYMMETRIC_GRID = 1;
CV_CALIB_CB_ASYMMETRIC_GRID = 2;
CV_CALIB_CB_CLUSTERING = 4;


//! the deprecated function. Use findCirclesGrid() instead of it.
function findCirclesGridDefault( image : pIplImage;  pattern_size: TCvSize;
                                          centers: pCvPoint2D32f;  flags : integer = CV_CALIB_CB_SYMMETRIC_GRID ) : boolean; cdecl;
```

But that doesn't work. 
Is there a way to use circle calibration with Delphi-openCV? 
Or what did i wrong in my header translation? 
(I never translated c/c++ headers before) 

greatings
Benedikt

**Comment by Laex** [comment]
Input Array, Size and InputArray - this C ++ classes and are not compatible with Delphi.

**Comment by BenediktS** [comment]
The openCV developer say that the C-API is deprecated. And everyone should use the c++ API ...  That means  there is no way to use the new openCV methodes in Delphi?  

%$§*§?/%§&$  ---  yeah i know, i should watch my language. 

Thanks anyway... I hope i find a way to get my work done with the "old" C-API functions.....
