### ISSUE TITLE
XE7 Component Install

### ISSUE THREAD

**Issue by LJGutierrez** [Laex/Delphi-OpenCV#45]
DEar Sirs,

I downloaded all the package and followed all the instruction. Everything is ok, except the component install. Using the right-click menu over the bpl file there is any option to install it, only to compile and build. If I try to add it to the package set, an error rise saying that the component can be installed because is not a design time package.

Can you help me with some hints about how install the components in Delphi-XE7??

Regards

Luis J. Gutierrez

**Comment by KristofVRA** [comment]
Hello,
the same issue here:  on Delphi XE5, only 3/4 files can be installed:

OpenCVXXX.dpk  -> !! no install button available !!
dclCommonOpenCVXXX.dpk  -> installation ok
dclVCLOpenCVXXX.dpk -> installation ok
dclFMXOpenCVXXX.dpk -> installation ok

Could you please assist us here ?

Best regards,
Kristof V.R.

**Comment by micha137** [comment]
Only Design time packages can be installed and these only as 32 bit versions, since the IDE is 32 bit only (at least XE3, don't know about newer IDEs).
