### ISSUE TITLE
D2010 version not compiling, ENDIF and IFEND differences before XE3

### ISSUE THREAD

**Issue by CFTechno** [Laex/Delphi-OpenCV#53]
It's not possible to install Delphi-OpenCV in D2010 (tested) and possible also XE1 and XE2 because of the change in the ENDIF and IFEND.

It used to be: 
IFDEF + ENDIF
IF + IFEND
but starting with XE3 using $IFEND and $ENDIF are interchangeable.

Because of this D2010 will give an error "E2029 $IFEND expected but $ENDIF found"

**Comment by CFTechno** [comment]
I had to change more in OpenCV.inc, ovc.core_c ovc.lib etc for every 
`
{$IFDEF DelphiOCVVersion_29}
  'video' +
{$ELSEIF DEFINED( DelphiOCVVersion_30)}
  'world' +
{$ENDIF}  <------- needs to be $IFEND
'

**Comment by Laex** [comment]
{$IF ....}
**{$IFEND}**

{$IFDEF ...}
**{$ENDIF}**
