### ISSUE TITLE
Can't connect to web camera with ErrorGetStream event

### ISSUE THREAD

**Issue by MikeErmakov** [Laex/Delphi-OpenCV#54]
Hi
Trying to connect to public web camera I got an ErrorGetStream event.
Delphi 10 Seattle
Opencv version 2.4.13
URL http://149.166.151.12:80/axis-cgi/mjpg/video.cgi

**Comment by Laex** [comment]
URL http://149.166.151.12:80/axis-cgi/mjpg/video.cgi?dummy=param.mjpg
See http://stackoverflow.com/questions/14204185/read-stream-from-specific-link/15487578#15487578

**Comment by MikeErmakov** [comment]
Не помогло. Ошибка идёт отсюда:
ocv.comp.FFMSource
sws_getCachedContext(nil, pCodecCtx^.Width, pCodecCtx^.Height, pCodecCtx^.pix_fmt, pCodecCtx^.Width,
      pCodecCtx^.Height, AV_PIX_FMT_BGR24, SWS_BILINEAR, nil, nil, nil) возвращает nil
Дебаггер показывает, что pCodecCtx^.Width = 0, pCodecCtx^.Height = 352, pCodecCtx^.pix_fmt = AV_PIX_FMT_YUVJ420P
