### ISSUE TITLE
Can't load package dclCommonOpenCV220.bpl. The specified module could not be found.

### ISSUE THREAD

**Issue by hungthuanmk** [Laex/Delphi-OpenCV#56]
I'm using Delphi XE8 and have a error when try to install components.
![image](https://cloud.githubusercontent.com/assets/12544161/17032515/ef891528-4fa3-11e6-8d7a-c6262ad0e1ed.png)

**Comment by Laex** [comment]
See README.MD
Copy OpenCV dll files
OS Windows 64-bit
Target platform 64-bit: (2),(4),(6) -> "C:\Windows\System32\"
Target platform 32-bit: (1),(3),(5),(7) -> "C:\Windows\SysWOW64\"
OS Windows 32-bit
Target platform 32-bit: (1),(3),(5),(7) -> "C:\Windows\System32\"

**Comment by 3ddark** [comment]
![screenshot_1](https://user-images.githubusercontent.com/5977787/47412276-f10a6000-d773-11e8-9ba0-34e1e7c82ebc.png)
Click Install but see this message. not a valid win32 application

**Comment by henrykim1004** [comment]
On Delphi 10.3 Rio, just adding DLL didn't solve problem 100%.
I have finally solved that by adding search path for
C:\Users\(my_user_id)\Documents\Embarcadero\Studio\20.0\Bpl
Here, (my_user_id) is your local folder user name.
BTW, thank you for your great work enabling OpenCV on delphi.

**Comment by henrykim1004** [comment]
On Delphi 10.3 Rio, I added "C:\Users\_your_id_\Documents\Embarcadero\Studio\20.0\Bpl" on search path to solve this problem.
