### ISSUE TITLE
ocv.cls.features2d does not compile (Delphi XE5)

### ISSUE THREAD

**Issue by TrueWodzu** [Laex/Delphi-OpenCV#59]
Hello,

Compiler returns this error message: 

> [dcc32 Error] ocv.cls.features2d.pas(46): E2003 Undeclared identifier: 'TKeyPoint'

Perhaps a record helper for TKeyPoint could solve the problem with record forward declaration?

**Comment by Laex** [comment]
Work on the module "ocv.cls.features2d" is not complete. Do not use it yet.
