### ISSUE TITLE
External exception e06d7363

### ISSUE THREAD

**Issue by anasbousselham** [Laex/Delphi-OpenCV#61]
Hi,
I use ocvImageOperation whit HaarCascade (hcPlateNumberRus), but when run i have this error
![untitled](https://cloud.githubusercontent.com/assets/9357948/20456245/9b15535a-ae6a-11e6-8fd3-7b7538a92e06.png)

**Comment by Laex** [comment]
sample code, please

**Comment by anasbousselham** [comment]
When I select hcPlateNumberRus i have this error

![untitled](https://cloud.githubusercontent.com/assets/9357948/20486148/993fd2ca-aff6-11e6-8424-2daa017caac2.png)

**Comment by Laex** [comment]
Use haarcascade_licence_plate_rus_16stages.xml

**Comment by anasbousselham** [comment]
I copied the file in the folder
![untitled](https://cloud.githubusercontent.com/assets/9357948/20488464/fab898e0-affe-11e6-845f-697f58095274.png)

**Comment by Laex** [comment]
Reinstall pakages

**Comment by anasbousselham** [comment]
I can't install the components, i have this error 

![err](https://cloud.githubusercontent.com/assets/9357948/20839837/fd5e2e3e-b8a5-11e6-82d7-6f62dd5c1708.png)

**Comment by Laex** [comment]
Pre remove previous packages (if installed) - menu: "Component" - "Install Packages" - all packets OpenCV (Remove button)
Make sure OpenCV files (* 2413? .dll) are copied to the respective directories (according readme.md)
Compile and then install the packages * 240.dpk

Error associated with the renaming of packages versii10.1 * 310.dpk in * 240.dpk and their installation without removing the old package.
