### ISSUE TITLE
Question/Problem

### ISSUE THREAD

**Issue by turric4n** [Laex/Delphi-OpenCV#62]
Hi,

I need to save imagedata bytes to stream (TStringStream) and everytime only return the first byte of data. 

For instance 

`TStringStream.Write(PByte(pIplImage.ImageData)^, pIplImage.ImageSize);` // only reads first byte of data.

**Comment by Laex** [comment]
Read - reads data.
Are you sure that TStringStream recorded more than one byte?

**Comment by turric4n** [comment]
> Read - reads data.

Sorry, typo error, TStringStream.Write(PByte(pIplImage.ImageData)^, pIplImage.ImageSize); 

Yes I load a .jpg image with `image := cvLoadImage(PAnsiChar(Path)` 

And then `TStringStream.Write(PByte(image.ImageData)^, image.ImageSize);` only gest the first byte of the image.

**Comment by Laex** [comment]
program Project1;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  System.Classes,
  ocv.highgui_c,
  ocv.core_c,
  ocv.core.types_c,
  ocv.imgproc_c,
  ocv.imgproc.types_c;

var
  image: pIplImage = nil;
  S:TStringStream;

begin
  try
    image := cvLoadImage('panorama_image1.jpg');

    S:=TStringStream.Create;
    S.Write(PByte(image.ImageData)^, image.ImageSize);
    S.SaveToFile('1.jpg');
    S.Free;
    cvReleaseImage(image);

  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.

**Comment by turric4n** [comment]
No way... Fills all the stream with the first byte of image data : 

![image](https://cloud.githubusercontent.com/assets/7852968/20755494/7ea2ff80-b70f-11e6-9a17-12bf7910c486.png)

**Comment by turric4n** [comment]
New project with your code :

![image](https://cloud.githubusercontent.com/assets/7852968/20755992/61b89842-b711-11e6-8b57-b240234f4924.png)

Another photo :

![image](https://cloud.githubusercontent.com/assets/7852968/20756051/960496be-b711-11e6-811f-bd4180a6bd2c.jpg)

The same problems, garbage stream :

![image](https://cloud.githubusercontent.com/assets/7852968/20756001/6ea9f3fc-b711-11e6-9d5a-5a2aa91ca2b0.png)

I am using RAD Berlin 10.1 and this libraries :

![image](https://cloud.githubusercontent.com/assets/7852968/20756140/d7fc1128-b711-11e6-994b-db25f688c905.png)

Thanks for all!

**Comment by Laex** [comment]
1.jpg this is not JPG
1.jpg - this data is the internal representation of the image "image.jpg" in pIplImage structure.
Once loaded into pIplImage image "image.jpg" using cvLoadImage, decoded image from JPG to bit representation in pIplImage format.

**Comment by turric4n** [comment]
Sorry for my ignorance... I should have supposed this. I wasted your time.
