### ISSUE TITLE
It's not an issue, it's another Demo of Real-Time Camera Face Recognition

### ISSUE THREAD

**Issue by blaisexen** [Laex/Delphi-OpenCV#65]
Test4: Updated to Unlimited Number of Faces :) Update > Names Displayed!
http://www.mediafire.com/file/xa15uo26ocpxciw/Delphi-OpenCv-FR-Test-Sample.zip

**Comment by edvaniojancy** [comment]
Could you please provide the source code for this demo please?

**Comment by blaisexen** [comment]
sure, here's the original source code:
http://www.mediafire.com/file/u38m8q9616mp6ae/Face_eDEMO_Delphi-OpenCV.zip

**Comment by edvaniojancy** [comment]
Thanks for the gal more I need an application equal to your demo if it could be available ejudaria much because there are others with the same doubts that I, thank you for your attention!
