### ISSUE TITLE
It's not an issue, a demo!

### ISSUE THREAD

**Issue by edvaniojancy** [Laex/Delphi-OpenCV#66]
It's not an issue, a demo!
How Delphi-OpenCV can work with Real Time Face Recognition! using Face Recognizers(eigenface,fisherface,lbphface)

**Comment by blaisexen** [comment]
There are many demo made by Master Laex, one of the demo he made for face recognition was this link:
https://github.com/Laex/Delphi-OpenCV/tree/master/samples/Classes/FaceRecognizer

So, with the face detection(included in the samples) I send and with that link(join them), and you know the basics of OpenCv like, cVimage2bitmap, iplImage2Bitmap, cvReSize, Bitmap2iplImage, cvCvTColor

You will arrived at the exact solution you want.  Look at openCv c/c++ codes then get ideas right on your own way for Delphi.

It's hard to be a software developer!  I learned that face detection and recognition for 3 months, and I think you could only do that correctly in a week time.
Good Luck!
