### ISSUE TITLE
cvCreateFileCapture always return nil on camera bosch NWD-495V03-20P

### ISSUE THREAD

**Issue by oesquedac** [Laex/Delphi-OpenCV#67]
Hi,

i try to use the demo VLCIPCameraCapture with a bisch NWD-495V03-20P, but any url is working, this is functionall for vlc video rtsp://192.168.0.141//rtsp_tunnel

The camera has no user and password and no port (i guess).

But the function cvCreateFileCapture always return nil, could you help me

**Comment by Laex** [comment]
rtsp://192.168.0.141//rtsp_tunnel -> rtsp://192.168.0.141/rtsp_tunnel
