### ISSUE TITLE
Troubles installing OpenCV 2.4.13 in XE10.1 upd 2

### ISSUE THREAD

**Issue by lgama** [Laex/Delphi-OpenCV#69]
Hello everyone, I'm trying to install the OpenCV 2.4.13 on Rad Studio XE 10.1 upd 2, but I have the following error:
"Can't find 'specific module"
This error is raised when I try to install any Component Project, for example, the following project:
<OPENCV-PROJECT-FOLDER>\source\component\ dclComponentOpenCV240.bpl
By the way, I couldn't find some required files listed on the installation guide such: _2413.dll and _2413d.dll, and 

(5) 32-bit in the C:\OpenCV\build\x86\vc12\bin\
(6) 64-bit in the C:\OpenCV\build\x64\vc12\bin\

Any idea what am I doing wrong?
Thanks so much.
=)

**Comment by jonahzheng** [comment]
OpenCV 2.4.13
https://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.13/opencv-2.4.13.exe/download
and install

**Comment by turric4n** [comment]
No problem wirh Berlin and Tokyo

**Comment by lgama** [comment]
Hello, my specific problem is that, the link to download the following files: _2413.dll and _2413d.dll requested by the installation guide is broken, so I don’t have those files, could you send them to me please?

Thanks so much.


De: Turrican [mailto:notifications@github.com]
Enviado el: Tuesday, May 9, 2017 12:34 PM
Para: Laex/Delphi-OpenCV <Delphi-OpenCV@noreply.github.com>
CC: LUIS ANTONIO GAMA MORENO <lgama_moreno@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Laex/Delphi-OpenCV] Troubles installing OpenCV 2.4.13 in XE10.1 upd 2 (#69)


No problem wirh Berlin and Tokyo

**Comment by blaisexen** [comment]
you can find this files when you install opencv2.4.13, then follow this steps: https://www.youtube.com/watch?v=cgo0UitHfp8
