### ISSUE TITLE
Error install Delphi Berlin not valid win32 application

### ISSUE THREAD

**Issue by alaxfilho** [Laex/Delphi-OpenCV#78]
Target platform 64-bit: (2),(4),(6) -> "C:\Windows\System32\"
Target platform 32-bit: (1),(3),(5),(7) -> "C:\Windows\SysWOW64\"

Ao Build OK 
dclFFMSource240.dpk
dclCommonOpenCV240.dpk
dclFMXOpenCV240.dpk
dclVCLOpenCV240.dpk

After install 
Error "not valid win32 application"

\System32
28/06/2017  09:54    <DIR>          .
28/06/2017  09:54    <DIR>          ..
19/05/2017  20:30        28.197.888 avcodec-57.dll
19/05/2017  20:30         2.240.000 avdevice-57.dll
19/05/2017  20:30         4.863.488 avfilter-6.dll
19/05/2017  20:30         5.403.136 avformat-57.dll
19/05/2017  20:30           676.352 avutil-55.dll
22/06/2017  00:35           627.368 msvcp140.dll
22/06/2017  00:35         1.001.280 msvcp140d.dll
17/12/2016  04:32         1.086.464 opencv_calib3d2413.dll
17/12/2016  04:34         2.704.384 opencv_calib3d2413d.dll
17/12/2016  04:33         1.186.816 opencv_contrib2413.dll
17/12/2016  04:34         3.489.280 opencv_contrib2413d.dll
17/12/2016  04:31         2.513.920 opencv_core2413.dll
17/12/2016  04:33         5.033.472 opencv_core2413d.dll
17/12/2016  04:32           779.264 opencv_features2d2413.dll
17/12/2016  04:34         2.132.480 opencv_features2d2413d.dll
16/12/2016  18:01         9.720.042 opencv_ffmpeg2413_64.dll
17/12/2016  04:32           529.920 opencv_flann2413.dll
17/12/2016  04:34         1.686.528 opencv_flann2413d.dll
17/12/2016  04:33           476.672 opencv_gpu2413.dll
17/12/2016  04:34         1.350.656 opencv_gpu2413d.dll
17/12/2016  04:32         2.255.360 opencv_highgui2413.dll
17/12/2016  04:34         4.842.496 opencv_highgui2413d.dll
17/12/2016  04:32         2.145.280 opencv_imgproc2413.dll
17/12/2016  04:34         4.592.128 opencv_imgproc2413d.dll
17/12/2016  04:33         1.379.328 opencv_legacy2413.dll
17/12/2016  04:34         3.609.088 opencv_legacy2413d.dll
17/12/2016  04:32           577.536 opencv_ml2413.dll
17/12/2016  04:34         1.449.472 opencv_ml2413d.dll
17/12/2016  04:33           613.888 opencv_nonfree2413.dll
17/12/2016  04:34         1.604.608 opencv_nonfree2413d.dll
17/12/2016  04:32           662.016 opencv_objdetect2413.dll
17/12/2016  04:34         2.103.808 opencv_objdetect2413d.dll
17/12/2016  04:33         2.431.488 opencv_ocl2413.dll
17/12/2016  04:34         4.668.928 opencv_ocl2413d.dll
17/12/2016  04:32           214.016 opencv_photo2413.dll
17/12/2016  04:34           684.032 opencv_photo2413d.dll
17/12/2016  04:33         1.123.840 opencv_stitching2413.dll
17/12/2016  04:34         3.031.552 opencv_stitching2413d.dll
17/12/2016  04:33           704.000 opencv_superres2413.dll
17/12/2016  04:34         1.808.384 opencv_superres2413d.dll
17/12/2016  04:32           419.840 opencv_video2413.dll
17/12/2016  04:34         1.055.744 opencv_video2413d.dll
17/12/2016  04:33           600.576 opencv_videostab2413.dll
17/12/2016  04:34         1.677.312 opencv_videostab2413d.dll
19/05/2017  20:30           122.368 postproc-54.dll
19/05/2017  20:30           345.600 swresample-2.dll
19/05/2017  20:30           533.504 swscale-4.dll
              47 arquivo(s)    120.955.602 bytes
               2 pasta(s)   95.937.318.912 bytes dispon¡veis

\SysWOW64
28/06/2017  09:54    <DIR>          .
28/06/2017  09:54    <DIR>          ..
27/06/2017  08:14        24.505.344 avcodec-57.dll
27/06/2017  08:14         2.011.648 avdevice-57.dll
27/06/2017  08:14         4.046.336 avfilter-6.dll
27/06/2017  08:14         5.145.600 avformat-57.dll
27/06/2017  08:14           669.184 avutil-55.dll
22/06/2017  00:35           438.080 msvcp140.dll
22/06/2017  00:35           749.888 msvcp140d.dll
17/12/2016  04:28           878.080 opencv_calib3d2413.dll
17/12/2016  04:30         1.896.448 opencv_calib3d2413d.dll
17/12/2016  04:29           988.672 opencv_contrib2413.dll
17/12/2016  04:30         2.560.000 opencv_contrib2413d.dll
17/12/2016  04:27         2.013.696 opencv_core2413.dll
17/12/2016  04:29         3.549.184 opencv_core2413d.dll
17/12/2016  04:28           648.704 opencv_features2d2413.dll
17/12/2016  04:30         1.546.752 opencv_features2d2413d.dll
16/12/2016  17:54        10.535.057 opencv_ffmpeg2413.dll
17/12/2016  04:27           417.280 opencv_flann2413.dll
17/12/2016  04:29         1.204.224 opencv_flann2413d.dll
17/12/2016  04:29           429.568 opencv_gpu2413.dll
17/12/2016  04:30           997.376 opencv_gpu2413d.dll
17/12/2016  04:28         1.985.536 opencv_highgui2413.dll
17/12/2016  04:30         3.824.128 opencv_highgui2413d.dll
17/12/2016  04:28         1.738.240 opencv_imgproc2413.dll
17/12/2016  04:29         3.229.184 opencv_imgproc2413d.dll
17/12/2016  04:28         1.144.320 opencv_legacy2413.dll
17/12/2016  04:30         2.686.976 opencv_legacy2413d.dll
17/12/2016  04:27           492.032 opencv_ml2413.dll
17/12/2016  04:29         1.097.216 opencv_ml2413d.dll
17/12/2016  04:29           538.624 opencv_nonfree2413.dll
17/12/2016  04:30         1.206.784 opencv_nonfree2413d.dll
17/12/2016  04:28           541.696 opencv_objdetect2413.dll
17/12/2016  04:30         1.532.416 opencv_objdetect2413d.dll
17/12/2016  04:29         1.932.800 opencv_ocl2413.dll
17/12/2016  04:30         3.510.272 opencv_ocl2413d.dll
17/12/2016  04:28           180.736 opencv_photo2413.dll
17/12/2016  04:29           485.888 opencv_photo2413d.dll
17/12/2016  04:29           956.416 opencv_stitching2413.dll
17/12/2016  04:30         2.208.256 opencv_stitching2413d.dll
17/12/2016  04:29           614.912 opencv_superres2413.dll
17/12/2016  04:30         1.329.152 opencv_superres2413d.dll
17/12/2016  04:28           334.336 opencv_video2413.dll
17/12/2016  04:29           754.688 opencv_video2413d.dll
17/12/2016  04:29           529.920 opencv_videostab2413.dll
17/12/2016  04:30         1.234.944 opencv_videostab2413d.dll
27/06/2017  08:14           116.736 postproc-54.dll
27/06/2017  08:14           293.888 swresample-2.dll
27/06/2017  08:14           509.440 swscale-4.dll
              47 arquivo(s)    100.240.657 bytes
               2 pasta(s)   95.937.970.176 bytes dispon¡veis

**Comment by Laex** [comment]
Install in the following sequence
dclCommonOpenCV*.dpk
dclFFMSource*.dpk
dclFMXOpenCV*.dpk
dclVCLOpenCV*.dpk
