### ISSUE TITLE
dclFFMSource250 cannot be installed

### ISSUE THREAD

**Issue by 172412593** [Laex/Delphi-OpenCV#79]
[dcc32 Fatal Error] ocv.comp.RegisterFFM.pas(27): F1026 File not found: 'OpenCV.inc'

**Comment by HuguesDug** [comment]
I confirm this problem under Delphi 10.2 Tokyo "Starter". It does not create any problem to use the various .pas and components.

**Comment by Laex** [comment]
Add path to "\Delphi-OpenCV\source\" in "Tools"-"Options"-"Library"-"Library path" delphi IDE
