### ISSUE TITLE
how to install delphi-opencv in 64bits windows without "designide"?

### ISSUE THREAD

**Issue by paladinzhh** [Laex/Delphi-OpenCV#81]
I install delphi-opencv 2.4.13 in 64bits windows. When build the package,meet an error "E2202 Required package 'designide' not found". Looking at the path this makes sense as the file refer to lib\win32. However, under lib\win64 there is no such file. how to install delphi-opencv in 64bits windows without "designide"?

**Comment by blaisexen** [comment]
hi,
try to put all the files in 1 folder, all the *.pas from of Delphi-OpenCV to the folder your compiling the application.

like this application I did, put all the files in 1 folder,
http://www.mediafire.com/file/u38m8q9616mp6ae/Face_eDEMO_Delphi-OpenCV.zip

I'll wait for your feedback,
good luck

**Comment by guiMohr** [comment]
Hi, i had the same problem, i @blaisexen solution but dind't work.
