### ISSUE TITLE
Few remaining issues following fix #80, wrong types in core and imgproc

### ISSUE THREAD

**Issue by HuguesDug** [Laex/Delphi-OpenCV#84]
Hello,

What a quick solution for the various elements I raised the last couple of days. Great work !

However, the last fix #80 is incomplete and leads to an new open point.

First, you forgot to update cvMinMaxLoc (I found at least this one). You give a PIplImage for source and mask, where it should be PCvArr.

Second, some modifications leads now to ambiguous compiling warning for some functions if you do pointed casting : 
CvCopy, CvMerge, cvAdd, CvAddS, cvSub, CvSubS, CvMul, CvDiv, CvScaleAdd, CvAddWeigthed, CvInRange, CvInRangeS, CvAnd, CvXorS, CvCountNonZero

You can safelly (I think), remove the prototype using PIplImage, keep the one with the PcvArr (that will work as well with PIplImage)  and, as a consequence remove the overloading of methods. Doing so should eliminate all the warnings.

First point is "critical".

Second point is "improvement".

Regards

**Comment by Laex** [comment]
Fixed
