### ISSUE TITLE
Features2d - Matcher/perspectiveTransform

### ISSUE THREAD

**Issue by RedSparrowEU** [Laex/Delphi-OpenCV#92]
Hi,

Thank you very much for the Git!
Would you please to extend it for working with this example:
http://docs.opencv.org/2.4/doc/tutorials/features2d/feature_homography/feature_homography.html

Thank you,
Greg

**Comment by Laex** [comment]
Features2d is based on classes (for example, Mat, vector). Creating wrappers for classes is time-consuming. While time is not enough.
