### ISSUE TITLE
why don't debug

### ISSUE THREAD

**Issue by shichuanq** [Laex/Delphi-OpenCV#93]
the project in sample don't debug ,why ?

**Comment by Laex** [comment]
Explain the question...

**Comment by shichuanq** [comment]
cannot be compiled in debug mode In the samples example, it can only be release

**Comment by Laex** [comment]
What messages are given? What happens when compiling in debug mode?

**Comment by Laex** [comment]
If you use components, you need to reinstall them...

**Comment by shichuanq** [comment]
display success，no message,Cannot breakpoint debugging,Cannot generate EXE file

**Comment by Laex** [comment]
EXE in '..\..\..\bin\Win32'?

**Comment by shichuanq** [comment]
cant debug  ，exe file run show message 'no vcruntime140d.dll'

**Comment by Laex** [comment]
See \Delphi-OpenCV\redist\VC14
