### ISSUE TITLE
Bug in components

### ISSUE THREAD

**Issue by HuguesDug** [Laex/Delphi-OpenCV#98]
A last one for today.

To reproduce do the following:
Drag and drop the camera source component
Drag and drop the rendering component
Connect one to the other
Put in the properties the enabled to true in the camera source, compile, run and quit with the cross top right of the window 

--> You have an seg fault.

I think some Destroy work have a problem.

If you now, in your own code, set to enable:=false the camerasource property on the event "canclose"... you close gently.

Regards

**Comment by Laex** [comment]
Fixed
